name: Scheduled database updates
on:
  push:
    paths:
      - .github/workflows/update-database.yml
  schedule:
    - cron: "0 9 * * *" # Every day at 9 AM UTC
  workflow_dispatch:

jobs:
  update-database:
    runs-on: macos-latest
    permissions:
      packages: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Update database
        run: |
          echo "Updated on $(date)" >> executables.txt

      - name: Print catabase
        run: |
          cat executables.txt

      - name: Install oras for pushing to GitHub Packages
        run: brew install oras

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io --username brewtestbot --password-stdin

      - name: Push to GitHub Packages
        run: |
          oras push --artifact-type application/vnd.homebrew.command-not-found.executables \
            ghcr.io/rylan12/command-not-found/executables:latest \
            executables.txt:text/plain
